### ISSUE TITLE
ntfy.sh support

### ISSUE THREAD

**Issue by Famku** [homelabapi/homelabapi#2]
Hi,

is it possible to add output support for ntfy.sh?

**Comment by Famku** [comment]
That was fast, thank you very much!

**Comment by gregdotca** [comment]
This is _almost_ ready to be closed. I ran into a bit of an issue while creating and converting over to an official docker image, but luckily I just figured it out a few minutes ago. I'm currently rebuilding the docker image, will do a final test, and then things should be ready to go.

I'll let you know once it's fully done.

**Comment by gregdotca** [comment]
Alright, it should be good-to-go now!
